### ISSUE TITLE
Feed the Tier4izer with the correct energy resolution curves

### ISSUE THREAD

**Issue by gipert** [mppmu/gerda-mage-sim#11]
We are currently using @wiesinger-ch's fork of gerda-metadata (see the `UTILS/post/gerda-metadata` submodule), what smearing curves is the Tier4izer using? We should update them to the final ones.

**Comment by gipert** [comment]
Bump!

We'd like to have the nicest resolution curves for the next PDFs production cycle. I see the Tier4izer currently reads them in from [`detector-data/ged-resolution-default.json`](https://github.com/wiesinger-ch/gerda-metadata/blob/tier4izer-metadata/detector-data/ged-resolution-default.json), what curves are those @wiesinger-ch? What should we use @cransom12? Our run list is currently `{ 53 ... 65, 67, 68 ... 79, 83 ... 89 }`.

Note that until we implement [this](https://github.com/mppmu/gerda-mage-sim/issues/2) they can include also the `NULL` dataset.

**Comment by cransom12** [comment]
I can't speak for what the tier4izer uses... If it's resolution curves per detector you're looking for, I can point you towards some PRELIMINARY ones in /nfs/gerda2/Calibration_PhaseII/SuperCalibrations/PhIIc/ZAC/calib.root, but since I haven't finished the new weighting procedure yet they are going to be updated at some point.

**Comment by wiesinger-ch** [comment]
Ciao, sorry for the late reply.
I can't fully recall what the current "default" curves correspond to.
I think they are the Gauss ones for PhaseIIb.

In any case we have to update them with the result from @cransom12 's supercalib anaylsis.

**Comment by gipert** [comment]
Ok so maybe it is worth to update the curves to the preliminary while we wait for the final ones. @cransom12 how are the preliminary curves you quoted produced? Is there only the new weighting procedure missing?

**Comment by cransom12** [comment]
Indeed, they are only missing the new weighting- however, they are the ZAC ones, not Gauss. To produce the Gauss curves would need the incorporation of the new calibration curves into v03.02.

**Comment by gipert** [comment]
That's good, we are currently using ZAC data! Please let us know when the new curves will be released.

@wiesinger-ch do you have a ready-use script to produce [`detector-data/ged-resolution-default.json`](https://github.com/wiesinger-ch/gerda-metadata/blob/tier4izer-metadata/detector-data/ged-resolution-default.json)?
