### ISSUE TITLE
Check of 2nbb pdfs composition and normalization

### ISSUE THREAD

**Issue by annkasch** [mppmu/gerda-mage-sim#17]

**Comment by ThWester** [comment]
![tnbb_check_bege](https://user-images.githubusercontent.com/2777014/36782260-b1d81a82-1c78-11e8-9e66-c60a9f21ade4.png)

this is how it looks for the BEGe dataset.
black is data.
red is scaled to the expected half-life:
log(2)*6.022e23mol*50kgyr*0.87/0.076kgmol^-1/1.9e+21yr / nPrimaries(100000002)
blue is what i get as a fit result from the detID spectra.

red looks a bit too low in my opinion, or is that just me? how many events do we expect from the 2nbb decay if we scale the previous results from 53-79 up to 53-89?

**Comment by annkasch** [comment]
From fits I get for the bege half lives of around 1.88e21 yr. As check I had a look at the pdf of channel 0 and the integral of the pdf seems to be too low.

**Comment by ThWester** [comment]
Also, the current pdfs (when only scaled with 1./nPrimaries) corresponds to an "efficiency" of only(?) 65% (full integral), which should include effects from active volume and disables/excluded detectors (only).

**Comment by annkasch** [comment]
The histograms in the file should by multiplied by

(ln(2) * N_A * T * M76) / (m76 * Nprim)

So, this means (forgetting the constants) I expect for integral of the hist from MC of for channel 0 something like (channel 0 seems to be on all runs)

(M76 / Nprim ) * ( t_k / T * m76_k / M_76 * integral ) =1/Nprim * 1 * 31.59 * integral = 4.001489e-01 (calculated with integral of M1_ch0)

But if I made a rough estimation and get:

m* f76 * eff = 0.627*0.877*0.888 = 4.882926e-01 with an detection efficiency which corresponds more or less to the fraction of the active volume. 
Compared to this we have a deviation of about 15 - 20 %

**Comment by gipert** [comment]
uhmm... this is weird, also because the discrepancy is relatively small. In this moment I really don't have a clue about why this happens, I guess you reviewed the normalisation procedure described in the Wiki and agree that it should be correct. Are you really sure the data you are fitting corresponds to the PDF? If yes it seems like there is some problem with not-ON detectors, which could explain the missing statistics in the PDF... What about the other activities in the fit? Did you spot some systematic changes with respect to the PDFs you used in the past? Is this only an issue of 2nbb?

**Comment by gipert** [comment]
> Also, the current pdfs (when only scaled with 1./nPrimaries) corresponds to an "efficiency" of only(?) 65% (full integral), which should include effects from active volume and disables/excluded detectors (only).

I've never done this calculation in the past, maybe the dead volume fraction + OFF/AC detectors could be the leading contribution of this 35%?

**Comment by gipert** [comment]
A first problem in the new 2nbb simulations I just spotted is that we simulate uniformly in the Ge mass and not in the Ge76 mass, so the normalisation described in the Wiki does not apply...

**Comment by annkasch** [comment]
>  Are you really sure the data you are fitting corresponds to the PDF? 


If the pdf of one single channel alone doesn't fit to the rough estimation the problem should be independent from the data set I use for the analysis. Assuming the combination and normalization of the pdfs is correct - in my understanding there are only two explanations for the discrepancy: 1) I miss that this channel was off or in AC in some runs and the life time I used isn't correct or 2)  the detection efficiency extracted from MC of the intrinsic decays is much larger than the AV (which would be in this case about 70% instead of the ~88% coming from the AV ) And if so, what is the reason for this additional losses of events?

**Comment by ThWester** [comment]
> I've never done this calculation in the past, maybe the dead volume fraction + OFF/AC detectors could be the leading contribution of this 35%?

the active volume is about 0.88.
events below the threshold of 150keV are less than 5%, so 0.95.
--> 0.88*0.95*x = 0.65

which means x, the fraction that comes from OFF/AC detectors is 0.77, or on average 8 out of the 37 enriched detectors are OFF/AC. Thats too many :/

> From fits I get for the bege half lives of around 1.88e21 yr.
This half-life looks much better than what I get though. I get 1.35e21 yr now, when I use 50kgyr exposure. I expect mine to be slightly smaller, because I dont add every background component, but I dont expect it to be that big of a difference, considering the 2nbb and K40/K42 components are the dominant ones.

**Comment by annkasch** [comment]
> A first problem in the new 2nbb simulations I just spotted is that we simulate uniformly in the Ge mass and not in the Ge76 mass, so the normalisation described in the Wiki does not actually apply...
So, you used the total mass applied in GERDA or only of the enr detectors?

**Comment by ThWester** [comment]
Just looking at the macro, the 2nbb is confined to all 40 detectors, including the naturals, weighted with the detector mass (as Luigi already mentioned). This means, the natCoax pdf of the 2nbb will be too high, while the pdf of the BEGe and enrCoax  compensate that and consequently will be too low (e.g. a lower half-life is required to scale it to the data).

Additionally, the exposure in this case would not just be 50kgyr (livetime and mass of enrCoax and BEGe dataset) with an enrFraction of 0.87, but also needs to take into account the mass and fraction of the natCoax.

Easiest fix would be to not generate primaries in the natCoax detectors. We only use the other two datasets and there are no coincidences expected from the 2nbb, so it should be fine.

**Comment by gipert** [comment]
> If I correct my obtained half-life by both effects, I get about 1.94e21yr.

Nice, so it seems to be the culprit.

> Easiest fix would be to not generate primaries in the natCoax detectors.

Actually enrichment fractions for EnrCoaxs are slightly different from BEGes, are we happy with this approximation?

**Comment by vonsturm** [comment]
Ok, I think I fixed this... new simulations are in the queue... once this is checked we can close the issue.

**Comment by gipert** [comment]
@vonsturm introduced `intrinsic_bege`, `intrinsic_coax` and `intrinsic_nat`, which in the end was the most natural fix, in bcc18b2.

**Comment by vonsturm** [comment]
@annkasch @ThWester please check and close the issue if everything is fine. new pdfs will be uploaded soon by @gipert

**Comment by gipert** [comment]
Is this fixed? @mppmu/gerda-bkg-modeling

**Comment by annkasch** [comment]
Yes. It seems to be fixed.

**Comment by gipert** [comment]
Ok, closing for now
