### ISSUE TITLE
Exclude NULL (-1) dataset

### ISSUE THREAD

**Issue by gipert** [mppmu/gerda-mage-sim#2]
`GD02D` and `GD91B` detectors should not be part of the final analysis dataset, we must exclude them by hand. Or we can use the DatasetManager?

**Comment by wiesinger-ch** [comment]
In principle we should handle this like the EnrBEGeNoPSD  issue.
They are not OFF but go into
02D -> NULL for all runs
91B -> NULL for [run0053,run0079]
32A -> NULL for [run0081,run009x]
see https://github.com/mppmu/gerda-ada/blob/master/src/core/GADatasetManager.cxx#L62

However, the NULL dataset could be handled with some add-on to the tier4izer.
It is just defined by a timestamp.

One idea concerning the EnrBEGeNoPSD dataset:
You could add a input to the pdf builder that uses the dataset fraction for each detector and scales the pdf (of each detector) by this number.
Extracting the number from tier4 should be easy (a la https://github.com/mppmu/gerda-ana-sandbox/blob/dev-lar/ana-tools/tools/DatasetFraction.C)

**Comment by gipert** [comment]
> In principle we should handle this like the EnrBEGeNoPSD issue.
> [...]
> However, the NULL dataset could be handled with some add-on to the tier4izer.
It is just defined by a timestamp.

Yes, it's the same issue, but while the EnrBEGeNoPSD problem is not critical because we don't take into account PSD in background modelling and thus we still have a "physically valid" dataset, here we miss to exclude "bad" detectors, and so at the opposite we have a dataset with events "we don't trust" (...am I right? Not completely sure)

> One idea concerning the EnrBEGeNoPSD dataset:
You could add a input to the pdf builder that uses the dataset fraction for each detector and scales the pdf (of each detector) by this number.

But this actually goes against our first motivation in doing this kind of post-processing (I mean splitting events according to run configurations), avoiding to "fake" statistics... isn't it?

> However, the NULL dataset could be handled with some add-on to the tier4izer. 
It is just defined by a timestamp

I don't know, maybe this is our only option at this point

**Comment by wiesinger-ch** [comment]
> But this actually goes against our first motivation in doing this kind of post-processing (I mean splitting events according to run configurations), avoiding to "fake" statistics... isn't it?

I think there is no problem of fake statistics in case we do this on a run-by-run basis.
E.g. only take 50% of the GD91B run0076 pdf if only 50% in EnrBEGe dataset for run0076.

Thinking about it, this could be also a json input to the tier4izer... but it might get a bit tricky.

**Comment by gipert** [comment]
I'm missing a point, so I'll ask it here: why don't we encode the NULL dataset in the RunConfigs? I mean, it seems to me something that concerns the run itself, a kind of intrinsic information... what's the argument against doing so? @mppmu/gerda-sw-management

**Comment by pandola** [comment]
@gipert In principle, there is no strong argument against that. On the other hand, the "NULL" dataset is a collection of "good" data (well calibrated, etc.) which you decide not to use for 0nbb analysis, e.g. due to bad energy resolution or missing PSD. So, the encoding of the datasetID is something that should be following the tier3. However, in principle there is no objection to code the datasetID info in the RunConfig. The only "con" is that you have to reprocess the tier3 for any change a-posteriori of the runconfig

**Comment by vonsturm** [comment]
Ok let's maybe not change now the handling of all this in the data production... I will exclude manually 02D and 89B from the mc pdfs and we think about the enrBEGeNoPSD data set in a later moment. This is not critical right now.

**Comment by vonsturm** [comment]
partly and temporarily hacked in bdfc65c

**Comment by wiesinger-ch** [comment]
Ciao,
as discussed at the meeting:
I will add the timestamp dependent part of the datasetID to the tier4izer.
Unfortunately there is no timestamp in the runconfigs.
We will have to feed it to the tier4izer.
In this case we could also retrieve the runconfig by timestamp.
This would need the $MU_CAL environment to be set, but could be useful in some cases.
How is this currently done?

Cheers,
Christoph

**Comment by pandola** [comment]
> How is this currently done?
What's exactly the question? ;)

**Comment by wiesinger-ch** [comment]
We have now run-wise post processing of the simulation.
I guess the runconfig input for the tier4izer is manually defined, is that correct?
In case we have to feed the timestamp (for the dataset), we can also get the runconfig from the RunConfigurationManager, isn't it?

**Comment by pandola** [comment]
Yep, indeed you need the timestamp only in order to retrieve the runconfig from the manager

**Comment by gipert** [comment]
Hey @wiesinger-ch, the Tier4izer is used in [`t4z-gen`](https://github.com/mppmu/gerda-mage-sim/blob/master/UTILS/post/t4z-gen.cxx). The RunConfigs names, as well as the livetimes, are read from [`run-livetime.json`](https://github.com/mppmu/gerda-mage-sim/blob/master/UTILS/post/run-livetime.json) and later given to `T4SimConfig::LoadRunConfig`. Up to now we loop over run IDs to have, in the end, a tier4ized file for each run. If you change the Tier4izer to accept timestamps the most simple thing would be to give it the timestamp for the specific run at each loop iteration, I guess... But actually this works if we assume that the dataset changes are strictly run-wise. Do you have other better ideas?

**Comment by wiesinger-ch** [comment]
I have currently problems to push to github repositories.. otherwise this would be enabled:
```
root [0] using namespace gada;
root [1] conf = new T4SimConfig();
root [2] conf->LoadMapping("/mnt/geda00/christoph/gerda-metadata/detector-data/mapping-default-depr.json");
root [3] conf->LoadRunConfig(1519727251);
root [4] sim = new TChain("fTree");
root [5] sim->Add("/mnt/e15/gu62foq/sim/pcalib/Bi214_berkeley/S3_857/output/pcalib.Bi214_S3_857_1000000_0.root");
root [6] handler = new T4SimHandler(sim,conf);
root [7] handler->SetBranchAddresses();
root [8] handler->GetEntry(0);
root [9] GADatasetManager manager;
root [10] manager.GetDatasetName(handler->GetGedEvent()->GetDatasetID()->at(0))
(std::string) "EnrBEGeNoPSD"
```
I guess this is what we need.
The datasetID will then pop up in the t4z output file. 

It only works if the runconfig is loaded by timestamp.
For this the $MU_CAL environment has to be set.

Passing the timestamps in a "data-like" way to the T4SimConfig would even allow to post process all simulations in one go.

**Comment by gipert** [comment]
I'm confused, in your example you show a `EnrBEGeNoPSD`-flagged event from a simulation... what does this mean?

**Comment by wiesinger-ch** [comment]
Well, since no PSD information is available (as usually at tier3 level) all "proper" BEGe events go into `EnrBEGeNoPSD`.
Only with another interface to the full tier4-calib metadata we could define between `EnrBEGe` and `EnrBEGeNoPSD`

**Comment by gipert** [comment]
Ok! 

> The datasetID will then pop up in the t4z output file.

How? As a branch in `fTree` I guess?

> Passing the timestamps in a "data-like" way to the T4SimConfig would even allow to post process all simulations in one go.

I don't quite get what you mean here

**Comment by wiesinger-ch** [comment]
> How? As a branch in fTree I guess?

yes, exactly like in the data (e.g. the summary files)

>> Passing the timestamps in a "data-like" way to the T4SimConfig would even allow to post process all simulations in one go.
> 
> I don't quite get what you mean here

In principle could define a timestamp for each simulated event (e.g. sampling the same timestamp profile as in the data).
By `conf->LoadRunConfig((ULong64_t) timestamp)` automatically the correct runconfig will be used.
 The datasetID is taken according to the timestamp.

The minimal change for the post-processing should be to:
- change the "runconfig" to something like "start_timestamp" in https://github.com/mppmu/gerda-mage-sim/blob/master/UTILS/post/run-livetime.json
- load  the runconfig via this timestamp in https://github.com/mppmu/gerda-mage-sim/blob/master/UTILS/post/t4z-gen.cxx#L177

This should do all the job.

**Comment by gipert** [comment]
Nice, I'll implement it and let you know how it goes

**Comment by gipert** [comment]
Everything seems to work properly, see #22
