### ISSUE TITLE
Missing volume confinement in larveto/sipm_ring/*/coin

### ISSUE THREAD

**Issue by gipert** [mppmu/gerda-mage-sim#20]
@BirgitSchneider you forgot to confine the source in `larveto/sipm_ring/*/coin`, see e.g. [raw-larveto-sipm_ring-Bi212-coin-000.mac](https://github.com/mppmu/gerda-mage-sim/blob/master/larveto/sipm_ring/Bi212/coin/log/raw-larveto-sipm_ring-Bi212-coin-000.mac)

**Comment by vonsturm** [comment]
Fixed and increased also stats. Give it a look and close the issue if it is fine ce5dfcd
