### ISSUE TITLE
Pa234m

### ISSUE THREAD

**Issue by vonsturm** [mppmu/gerda-mage-sim#27]
excitation energy is 73.92keV (NuDat/geant4)
- coin: no excitation energy used (bug!)
- edep: 78keV used (ok but should be redone)

**Comment by vonsturm** [comment]
- macros are changed 7eabc85
- check and launch simulations

**Comment by vonsturm** [comment]
- simulations running

**Comment by vonsturm** [comment]
Checked and is still not OK... better but has still a bug. The 809keV line is not visible in spectrum. The actual true excitation energy of Pa234m should be 83.92keV (0- level) not 73.92keV (3+ level). Source: recommended data

**Comment by vonsturm** [comment]
![a234_z90](https://user-images.githubusercontent.com/2419151/37411612-7b77f576-27a3-11e8-9765-a737a53c037b.png)

The difference between 73.92keV and 83.92keV excitation energy is only the efficiency, the spectral form looks the same. There is however a line at ~810keV which is not showing up her. (Shows up in the partial chain of U238 in the Legend simulations though.) Any ideas are welcome... From the Pa234m gamma radiation table I would not expect this line to show up... http://www.nucleide.org/DDEP_WG/Nuclides/Pa-234m_tables.pdf

**Comment by ThWester** [comment]
![pa234m_scheme](https://user-images.githubusercontent.com/2777014/37415893-cf4ca710-27ac-11e8-8767-605d5beee452.png)

Seems to be a summation of the 766keV gamma and the 43 keV gamma/ce that should always come in coincidence. I guess the geometry in the Legend simulation allows the detection of the 43keV, while ours does not?

**Comment by vonsturm** [comment]
That is a good guess also because the Gerda 766keV line is much stronger than the Legend line. Can be that Matt made the simulations without dead layer...
