### ISSUE TITLE
K42 above each MS

### ISSUE THREAD

**Issue by vonsturm** [mppmu/gerda-mage-sim#29]
K42 does not seem to fit so well. In principle we could have a different contribution for each cable string going to the MS due to different accumulation on the cables (different quality of shielding e.g.)

- Simulate a K42 volume above each MS with the same volume each and allow for different contributions from the different volumes

**Comment by vonsturm** [comment]
I am preparing macros for cylindrical volumes above each MS starting at the ms-tops. Radius 5cm, Height 20cm which is of course arbitrary. @ThWester Maybe feeding them independently into the fit we can kill the K42 radial asymmetry.

**Comment by vonsturm** [comment]
Jobs are in the queue

**Comment by gipert** [comment]
> Jobs are in the queue

![telemmglpict000002004414_trans_nvbqzqnjv4bqm37qciwr9ctrqmimdqvx7m-erykw1yvjehinaxgsq0c](https://user-images.githubusercontent.com/20358192/37173048-d9c507da-2312-11e8-808a-e18298b691dc.jpeg)
