### ISSUE TITLE
Missing simulations for larveto/copper_shroud/Bi212/coin larveto/copper_shroud/Pb214/coin

### ISSUE THREAD

**Issue by gipert** [mppmu/gerda-mage-sim#31]
They are needed for `larveto/copper_shroud/Tl208/coin` and `larveto/copper_shroud/Bi214/coin`

**Comment by annkasch** [comment]
And larveto/copper_shroud/Ac228/coin

**Comment by ThWester** [comment]
Pb214 is not really necessary for the coincidences, because its contribution is way lower than Bi214. Especially for such a far distance source, where you probably would need a lot of primaries to get sufficient statistics by itself.

**Comment by vonsturm** [comment]
larveto/copper_shroud/Bi212/coin 100x1E8 in queue
