### ISSUE TITLE
Separate pdfs for n+ components on BEGe and Coax?

### ISSUE THREAD

**Issue by ThWester** [mppmu/gerda-mage-sim#4]
The model fit by AnnKa results in different acitivties for K42 on the nplus surface of BEGe and Coax detectors.

With just one pdf including both detector contributions, we would not be able to recreate this.
Using M1_enrBEGe/M1_enrCoax (or filtering the bins of M1_all_1525 corresponding to each detector type in case of the DetID distributions)
is not accurate, as Coax and BEGe affect each other through coincidences.

**Comment by vonsturm** [comment]
So what exactly are you suggesting? To separate in two simulations one on BEGe p+ contacts and one on Coax p+ contacts?

**Comment by ThWester** [comment]
The simulations already exist for each detector.

The change would just be for the combination step, where instead of combining all the simulations to one pdf, we combine to one pdf generated from the BEGe simulations and one pdf generated from the Coax simulations.

Oh, and I was talking about n+, but p+ is probably the same then.

**Comment by gipert** [comment]
I think we can then go for splitting the `nplus` (`pplus`) folder in `nplus_bege` and `nplus_coax` (`pplus_bege` and `pplus_coax`), so we don't have to change anything in the post-processing machinery, is it OK?

**Comment by gipert** [comment]
Should we also split `coax` in `enrcoax` and `natcoax`?

**Comment by ThWester** [comment]
I would say no. Both got similar geometry, so there should not be a difference in K42 on their surface from this point of view.

**Comment by gipert** [comment]
Implemented in fad3ae1.
