### ISSUE TITLE
Channel-wise simulations are bad

### ISSUE THREAD

**Issue by gipert** [mppmu/gerda-mage-sim#5]
If you join together channel-wise simulations you don't have across-the-whole-volume-random-generated primaries, and this creates an issue when splitting the total tree according to runconfigs.

**Comment by vonsturm** [comment]
Ok this one is a bit tricky... gen-pdf like we do it now does not work in general for simulations done separately for single channels. Splitting the events according to the livetime of each run results in runs where only one detector was exposed. The right thing to do is to split each of these simulations separately. This has to be fixed... Let's think about this tomorrow.

**Comment by gipert** [comment]
Oh crap, that's right, big bug! We should kind of shuffle the events in the summed tree before splitting it into run-wise subtrees...

**Comment by gipert** [comment]
We could just get the total number of entries, [shuffle it](http://en.cppreference.com/w/cpp/algorithm/random_shuffle), and then call `TTree::GetEntry` on this shuffled ensemble. Would this be the less painful workaround?

**Comment by gipert** [comment]
Apparently reading a TTree in non-sequential order is incredibly time-consuming because of how the class works, we need another solution...
